// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/items/SpaceDog.tsx": () => import("../components/mockups/items/SpaceDog.tsx"),
  "./components/mockups/zoom-pixel/PixelFarm.tsx": () => import("../components/mockups/zoom-pixel/PixelFarm.tsx")
};
